// templates/vue-nuxt/enterprise/pages/index.vue
<template>
	<Layout>
		<h1>Enterprise Nuxt Home</h1>
		<pre>{{ data }}</pre>
	</Layout>
</template>
<script setup>
import { ref, onMounted } from 'vue'
import Layout from '../components/Layout.vue'
import { fetchData } from '../services/api'
const data = ref(null)
onMounted(async () => {
	data.value = await fetchData()
})
</script>

// templates/react-nextjs/enterprise/pages/index.js
import Layout from '../components/Layout'
import { fetchData } from '../services/api'
import { useEffect, useState } from 'react'
export default function Home() {
	const [data, setData] = useState(null)
	useEffect(() => {
		fetchData().then(setData)
	}, [])
	return (
		<Layout>
			<h1>Enterprise Home</h1>
			<pre>{JSON.stringify(data, null, 2)}</pre>
		</Layout>
	)
}
