// templates/qwik/standard/src/components/Layout.tsx
import { component$ } from '@builder.io/qwik'

export default component$(({ children }: { children: any }) => {
	return (
		<div>
			<header>
				<h2>Qwik Standard Project</h2>
			</header>
			<main>{children}</main>
			<footer>
				<small>&copy; 2025 Qwik Standard</small>
			</footer>
		</div>
	)
})

// templates/remix/enterprise/app/components/Layout.tsx
import React from 'react'

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<div>
			<header>
				<h2>Remix Enterprise Project</h2>
			</header>
			<main>{children}</main>
			<footer>
				<small>&copy; 2025 Remix Enterprise</small>
			</footer>
		</div>
	)
}
